name: Build U-Boot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build U-Boot
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl device-tree-compiler gcc-arm-none-eabi gcc-aarch64-linux-gnu libudev-dev libusb-1.0-0-dev dh-autoreconf
          python -m pip --no-python-version-warning --disable-pip-version-check install -r requirements.txt
      - name: Clone repositories
        run: |
          git clone --depth 1 $GITHUB_SERVER_URL/rockchip-linux/rkbin
          git clone --depth 1 $GITHUB_SERVER_URL/u-boot/u-boot

      - name: Compile U-Boot
        working-directory: u-boot
        run: |
          #cp ../rkbin/bin/rk33/rk3399_bl31_v1.35.elf atf-bl31
          export BL31=../rkbin/bin/rk33/rk3399_bl31_v1.35.elf
          export ARCH=arm64
          sed -i -e 's/-Werror//' Makefile
          #cp ../rk3399-evb.dts arch/arm/dts/rk3399-evb.dts
          #echo "CONFIG_BOOTDELAY=5" >> configs/evb-rk3399_defconfig
          make evb-rk3399_defconfig
          make CROSS_COMPILE=aarch64-linux-gnu- -j4
      - name: Create trust.img
        working-directory: rkbin
        run: |
          ./tools/trust_merger RKTRUST/RK3399TRUST.ini
          
      - name: Create uboot.img
        working-directory: rkbin
        run: |
           ./tools/loaderimage --pack --uboot ../u-boot/u-boot-dtb.bin uboot.img
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rk3399-uboot
          path: rkbin/*.img
