name: Build U-Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build U-Boot
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone U-Boot
        run: |
          git clone --depth=1 https://github.com/rockchip-linux/u-boot
      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: u-boot
        run: |
          sudo apt install gcc-aarch64-linux-gnu gcc-arm-none-eabi -y
      - name: Build ATF
        run: |
          git clone --depth 1 https://github.com/ARM-software/arm-trusted-firmware.git
          cd arm-trusted-firmware
          make realclean
          make CROSS_COMPILE=aarch64-linux-gnu- PLAT=rk3399
          cd ..
      - name: Build U-Boot
        working-directory: u-boot
        run: |
          export BL31=../arm-trusted-firmware/build/rk3399/release/bl31/bl31.elf
          sed s/"-fshort-wchar -Werror"/"-fshort-wchar -w"/g Makefile
          make evb-rk3399_defconfig
          make CROSS_COMPILE=aarch64-linux-gnu-
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: JJ31-uboot
          path: |
            u-boot/*.bin
            u-boot/*.img
          if-no-files-found: ignore
