name: Build U-Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout U-Boot repository
      uses: actions/checkout@v2
      with:
        repository: u-boot/custodians/u-boot-rockchip

    - name: Download and extract GCC cross-compiler
      run: |
        curl -OL https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
        tar xvf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz -C $(pwd)

    - name: Build U-Boot
      run: |
        make CROSS_COMPILE=aarch64-linux-gnu- evb-rk3399_defconfig
        make ARCH=arm CROSS_COMPILE=$(pwd)/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
        make u-boot.itb

    - name: Upload U-Boot artifacts
      uses: actions/upload-artifact@v2
      with:
        name: u-boot
        path: |
          u-boot/u-boot.bin
          u-boot/u-boot.itb
          u-boot/spl/u-boot-spl.bin
          u-boot/tpl/u-boot-tpl.bin
