name: Build U-Boot v2017.09-rc4

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build U-Boot
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
               
      - name: Get U-Boot source
        run: |
          wget https://github.com/rockchip-linux/u-boot/archive/refs/tags/release-20171218.zip
          unzip *.zip
          mv u-boot* u-boot
        
      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: u-boot
        run: |
          sudo apt install device-tree-compiler gcc-aarch64-linux-gnu
          git clone https://github.com/rockchip-linux/rkbin --depth 1 ../rkbin
        
      - name: Build U-Boot
        working-directory: u-boot
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          mkdir out
          make evb-rk3399_defconfig O=out
          #make -j2 dtbs
          ./make.sh evb-rk3399 O=out
 
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: evb-rk3399-uboot
          path: |
            u-boot/*.bin 
            u-boot/*.img
            gpt.img.xz
          if-no-files-found: ignore
